modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/ZigyTheBird/BendableCuboids/issues"
license = "MIT License"

[[mods]]
modId = "bendable_cuboids"
version = "${version}"
displayURL = "https://github.com/ZigyTheBird/BendableCuboids"
displayName = "Bendable Cuboids Library"
authors = "KosmX, Zigy"
description = '''
Adds model cubes that can be bent, for example like arms in MC Story Mode!
'''
#logoFile = ""

[[mixins]]
config = "bendable_cuboids.mixins.json"

[[dependencies.bendable_cuboids]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bendable_cuboids]]
modId = "ears"
type = "incompatible"
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bendable_cuboids]]
modId = "skinlayers3d"
type = "incompatible"
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"
