modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/ZigyTheBird/BendableCuboids/issues"
license = "MIT License"

[[mods]]
modId = "bendable_cuboids"
version = "${version}"
displayURL = "https://github.com/ZigyTheBird/BendableCuboids"
displayName = "Bendable Cuboids Library"
authors = "KosmX, Zigy"
description = '''
Adds model cubes that can be bent, for example like arms in MC Story Mode!
'''
#logoFile = ""

[[mixins]]
config = "bendable_cuboids.mixins.json"

[mods."sodium:options"]
"mixin.features.render.entity" = false
"mixin.features.render.entity.cull" = true
"mixin.features.render.entity.shadow" = true

[[dependencies.bendable_cuboids]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"